export const IMAGE = {
  DEFAULT_BOOTH_THUMBNAIL: "/images/DEFAULT_BOOTH_THUMBNAIL.png",
  NOTICEE_DUE_TIME: "/images/NOTICE_DUE_TIME.png",
  NOTICE_MAX_WAITING: "/images/NOTICE_MAX_WAITING.png",
  NOTICE_NO_SHOW: "/images/NOTICE_NO_SHOW.png",
  NAVIGATION_ON_BOARDING: "/images/NAVIGATION_ONBOARDING.svg",
};
